### ISSUE TITLE
License

### ISSUE THREAD

**Issue by titouantanguy** [cvkem/jaeger_stats#2]
Hi!
Thanks for the nice tool ! Very useful!
However I see there is no license and was thus not certain to what extent would I be allowed to use it?
Would you agree to make your code open source and specify that by adding an MIT or BSD open source license file to this project?

Thanks much for the hard work!

**Comment by cvkem** [comment]
Hi,

Thanks for your message.
I suppose the Apache licenses or Eclipse licenses are also quite permissie.
So I suppose these licenses will fit your purpose too.

Regards,
Cees

**Comment by titouantanguy** [comment]
Hi,

I am not a license expert either, I was merely suggesting the couple ones I know :).
It is your work, so whatever you feel suits you best is fine by me!

Best

**Comment by cvkem** [comment]
The project has a dual License now, MIT + Apache-2, which is the same licenses as used by the Rust language.
