### ISSUE TITLE
trace_analysis: bson: InvalidDocumentKey(Int32(500))

### ISSUE THREAD

**Issue by jayvdb** [cvkem/jaeger_stats#5]
After getting past #3, I see
```
thread 'main' panicked at src/stats/file/bson.rs:17:61:
called `Result::unwrap()` on an `Err` value: InvalidDocumentKey(Int32(500))
```

Using `-o json` works.

**Comment by cvkem** [comment]
I have added bincode and json and used them a lot. However, bincode does not guarantee that the binary format is stable across Rust-compiler versions, so it is not suited for longer term storage. Json is slower to process, and results in large files.
For that reason I investigated bson, but that did not provide sufficient benefits, so therefore I switched back to json.
I consider to remove the bson option for that reason as others also run into issues with it.

**Comment by jayvdb** [comment]
no worries ; we're happy to use json
